### ISSUE TITLE
can't work after some minor change 

### ISSUE THREAD

**Issue by yiqing** [romi45/yii2-seo-behavior#6]
https://github.com/agilov/yii2-seo-behavior/blob/master/components/SeoPatternHelper.php#L168
~~~php
	public static function replace($patternString, $model) {
		//$patternString = '%%model_title%% %%sep%% %%appParam_contactEmail%% %%viewParam_titleSeparator%% %%appConfig_name%%';
		// $replacedString = '';
		$replacedString = $patternString;  // after change to this ， it works！
		...
~~~

please check the logic ！

if i don't use the pattern ，second time when i edit the form  the seoXxx will become blank ! 
seems that this replace function will do replace non-pattern string to empty .

**Comment by agilov** [comment]
Hello. 
Please write to this guy: https://github.com/igorveremsky and describe the problem.
He wrote this logic and i think can quickly fix this bug.

**Comment by yiqing** [comment]
ok thanks ！

**Comment by igorveremsky** [comment]
@yiqing thanks for you reply. I find that if patterns was not found in model seo property it replaced with empty string. Fix it at https://github.com/agilov/yii2-seo-behavior/commit/d953ee1ae91e2f303789a7df036a418f1515fbe2 . Can you please update packages to 
1.0.7 version and give us a feedback is it fix you problem? Thanks.

**Comment by igorveremsky** [comment]
@yiqing hi, pls give a feedback, is problem still need to fix?

**Comment by yiqing** [comment]
@igorveremsky  sorry for late reply  , i am too busy recently .  seems ok now! thanks .
