### ISSUE TITLE
Postgres Database Exception (#42883)

### ISSUE THREAD

**Issue by RodrigoDornelles** [romi45/yii2-seo-behavior#9]
The extension worked normally in development mode,
went to deploy in production I'm having problems inserting records.

### Error Log

```
PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: character varying = integer
LINE 1: SELECT * FROM "seo_content" WHERE ("model_id"=$1) AND ("mode...
                                                     ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.41 |
| PHP version      |  7.4 | 
| Postgres SQL Version | 13.3 |
| Operating system | Centos 7 + Plesk |

**Comment by agilov** [comment]
Please update to 1.1.1 - it contains fix for this issue. Model id is casted to string. Note that this fix is not tested and if it didn't solve thee issue - please reopen it.
